inherit_from: .rubocop_todo.yml

AllCops:
  # Rubyバージョン指定
  TargetRubyVersion: 2.5.7
  # 除外
  Exclude:
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - !ruby/regexp /old_and_unused\.rb$/

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

#文字数の最大値:250
Metrics/LineLength:
  Max: 250

#マジックコメント(ソースファイルの文字コードを指定)使用すると文字列のリテラル(直接記述した定数)がデフォルトで不変を回避
Style/FrozenStringLiteralComment:
  Enabled: false
